server:
  port: 8080
  error:
      include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/consulthi_db
    username: consulthi_user
    password: 'temp'
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      # O Hibernate criará/atualizará as tabelas
      ddl-auto: update
    properties:
      hibernate:
        # Mostra o SQL gerado no console
        show_sql: true
        format_sql: true
        # Dialeto específico para PostgreSQL
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuração de logging
logging:
  level:
    # Mostra todas as queries SQL geradas
    org.hibernate.SQL: DEBUG
    # DEBUG para desenvolvimento
    com.ThimoteoConsultorias.Consulthi: DEBUG