server:
  port: 8080
  error:
      include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/consulthi_db
    username: consulthi_user
    password: 'temp'
    driver-class-name: org.postgresql.Driver

  devtools:
    livereload.enabled: true
    restart.exclude: static/**
  
  thymeleaf:
    cache: false 
  
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  file:
    # Salva todos os logs em um arquivo chamado 'consulthi.log'
    # Este arquivo aparecer√° na raiz do seu projeto.
    name: consulthi.log
  
  level:
    org.springframework.web: DEBUG
    
    com.fasterxml.jackson.databind: DEBUG
    # Mostra todas as queries SQL geradas
    org.hibernate.SQL: DEBUG
    # DEBUG para desenvolvimento
    com.ThimoteoConsultorias.Consulthi: DEBUG